name: Update LLMS.txt

on:
  schedule:
    # Runs every week on Monday at 3 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-llms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml
    
    - name: Run LLMS update script
      run: |
        python update_llms_txt.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "l.drontmann@lively.nl"
        git config --local user.name "Lars"
        git add llms.txt
        git diff --staged --quiet || git commit -m "Auto-update llms.txt - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload to Webflow (if configured)
      run: |
        # Optional: Add upload script here
        echo "LLMS.txt updated successfully!" 